spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5430/postgres
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ManychStepanAlekseevichBIB13414010
  expiration: 3600000